import { DateUtils } from '$lib/Utils';
import { type ProjectData, ProjectType } from '$lib/types';

export const externalProjects: ProjectData[] = [
    {
        title: 'Echoes',
        url: 'https://longitude.studio/Echoes',
        date: DateUtils.pacificDate('2024-04-02'),
        type: ProjectType.Generative,
    },
    {
        title: 'Polka Thoughts',
        url: 'https://longitude.studio/Polka',
        date: DateUtils.pacificDate('2024-03-29'),
        type: ProjectType.Live,
    },
    {
        title: 'Gear Up',
        url: 'https://longitude.studio/GearUp',
        date: DateUtils.pacificDate('2024-02-24'),
        type: ProjectType.Generative,
    },
    {
        title: 'Good Wording, LLC',
        url: 'https://goodword.ing',
        date: DateUtils.pacificDate('2024-1-17'),
        type: ProjectType.Landing,
    },
    {
        title: 'Wave Grid',
        url: 'https://longitude.studio/WaveGrid',
        date: DateUtils.pacificDate('2023-11-14'),
        type: ProjectType.Live,
    },
    {
        title: 'Sketchbook v0.2',
        url: 'https://github.com/flatpickles/sketchbook/releases/tag/v0.2.0',
        date: DateUtils.pacificDate('2023-11-06'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Sketchbook v0.1',
        url: 'https://github.com/flatpickles/sketchbook/releases/tag/v0.1.0',
        date: DateUtils.pacificDate('2023-10-01'),
        type: ProjectType.WebApp,
    },
    {
        title: "That's a Moiré",
        url: 'https://longitude.studio/ThatsAMoire',
        date: DateUtils.pacificDate('2023-07-28'),
        type: ProjectType.Generative,
    },
    {
        title: 'ART 125A Projects',
        url: 'https://www.instagram.com/p/CvFtsR7vFuG/',
        date: DateUtils.pacificDate('2023-07-24'),
        type: ProjectType.Image,
    },
    {
        title: 'Contours',
        url: 'https://longitude.studio/Contours',
        date: DateUtils.pacificDate('2023-07-21'),
        type: ProjectType.Generative,
    },
    {
        title: 'Plotter Base (Vlog)',
        url: 'https://www.instagram.com/p/CukwOD_rgGq/',
        date: DateUtils.pacificDate('2023-07-11'),
        type: ProjectType.Video,
    },
    {
        title: 'Solar Praxis',
        url: 'https://longitude.studio/SolarPraxis',
        date: DateUtils.pacificDate('2023-06-14'),
        type: ProjectType.Generative,
    },
    {
        title: 'Relax',
        url: 'https://longitude.studio/Relax',
        date: DateUtils.pacificDate('2023-06-03'),
        type: ProjectType.Generative,
    },
    {
        title: 'Concentric',
        url: 'https://longitude.studio/Concentric',
        date: DateUtils.pacificDate('2023-05-14'),
        type: ProjectType.Generative,
    },
    {
        title: 'Essentia',
        url: 'https://longitude.studio/Essentia',
        date: DateUtils.pacificDate('2023-04-23'),
        type: ProjectType.Live,
    },
    {
        title: 'Beastly Groove',
        url: 'https://www.soundslice.com/slices/vVlyc/',
        date: DateUtils.pacificDate('2023-04-20'),
        type: ProjectType.Transcription,
    },
    {
        title: 'Is It Perfect?',
        url: 'https://perfect.flatpickles.com/',
        date: DateUtils.pacificDate('2023-04-13'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Convergence',
        url: 'https://convergence.flatpickles.com/',
        date: DateUtils.pacificDate('2023-04-10'),
        type: ProjectType.WebApp,
    },
    {
        title: 'World Wide Webcam',
        url: 'https://wwwebcam.flatpickles.com/',
        date: DateUtils.pacificDate('2023-03-06'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Aurora Vibes',
        url: 'http://longitude.studio/AuroraVibes',
        date: DateUtils.pacificDate('2023-02-15'),
        type: ProjectType.Live,
    },
    {
        title: 'flatpickles.com',
        url: 'https://github.com/flatpickles/flatpickles.com',
        date: DateUtils.pacificDate('2023-01-23'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Face Replace',
        url: 'https://github.com/flatpickles/ML-Experiments/blob/main/Face_Replace.ipynb',
        date: DateUtils.pacificDate('2023-02-03'),
        type: ProjectType.Notebook,
    },
    {
        title: 'Ethereal Goop',
        url: 'http://longitude.studio/EtherealGoop',
        date: DateUtils.pacificDate('2022-10-29'),
        type: ProjectType.Live,
    },
    {
        title: 'Mandelbrot Set Viewer',
        url: 'http://longitude.studio/MandelbrotSet',
        date: DateUtils.pacificDate('2022-09-29'),
        type: ProjectType.Live,
    },
    {
        title: 'Rectilinear',
        url: 'http://longitude.studio/Rectilinear',
        date: DateUtils.pacificDate('2022-09-14'),
        type: ProjectType.Generative,
    },
    {
        title: 'Sketchbook (Legacy)',
        url: 'http://skbk-legacy.flatpickles.com/#no-signal',
        date: DateUtils.pacificDate('2022-08-15'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Glitchy',
        url: 'https://editor.isf.video/shaders/62bb5b57ad0a68001af75b57',
        date: DateUtils.pacificDate('2022-07-11'),
        type: ProjectType.VideoEffect,
    },
    {
        title: 'GutenBard',
        url: 'https://gutenbard.vercel.app',
        date: DateUtils.pacificDate('2022-06-14'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Floppy Disk',
        url: 'http://longitude.studio/FloppyDisk',
        date: DateUtils.pacificDate('2022-04-08'),
        type: ProjectType.Live,
    },
    {
        title: 'Flat Picks - Season 4',
        url: 'https://open.spotify.com/playlist/3hd6tpg5ZUsme35lzG48V2?si=0e059e9fa00e4384',
        date: DateUtils.pacificDate('2021-12-31'),
        type: ProjectType.Playlist,
    },
    {
        title: 'Music for Ryan & Jessica',
        url: 'https://paper.dropbox.com/doc/Music-for-Ryan-Jessica--BQSQtmtxGhjczmXJI3UuxdaZAQ-hhmATgKFzLjcsaqbxIE5x',
        date: DateUtils.pacificDate('2021-08-08'),
        type: ProjectType.Playlist,
    },
    {
        title: 'What a Day (Kiefer Solo)',
        url: 'https://www.soundslice.com/slices/qfMDc/',
        date: DateUtils.pacificDate('2021-04-21'),
        type: ProjectType.Transcription,
    },
    {
        title: 'Wobbly Video Effect',
        url: 'https://editor.isf.video/shaders/624d2c1efa14610014854030',
        date: DateUtils.pacificDate('2021-01-27'),
        type: ProjectType.VideoEffect,
    },
    {
        title: 'Warpy Video Effect',
        url: 'https://editor.isf.video/shaders/624d2c75fa14610014854058',
        date: DateUtils.pacificDate('2021-01-01'),
        type: ProjectType.VideoEffect,
    },
    {
        title: 'Flat Picks - Season 3',
        url: 'https://open.spotify.com/playlist/442CwkAO1CNU0TEnstZQc6?si=xABKoa-WS7S6vaI4RLHDIg',
        date: DateUtils.pacificDate('2021-10-10'),
        type: ProjectType.Playlist,
    },
    {
        title: "What's Old Is New Again",
        url: 'https://hic.af/objkt/527978',
        date: DateUtils.pacificDate('2021-11-10'),
        type: ProjectType.Video,
    },
    {
        title: 'Flat Picks - Season 2',
        url: 'https://open.spotify.com/playlist/5QB5698lV4DguTVmvCZY9W?si=JGKeOjC7TeS8hqx9lhnBlg',
        date: DateUtils.pacificDate('2019-10-12'),
        type: ProjectType.Playlist,
    },
    {
        title: 'Flat Picks - Season 1',
        url: 'https://open.spotify.com/playlist/2FV9kc9KxDPRIPiUMgHtwv?si=wkkoRYEKQGKUTTijPh_Xcw',
        date: DateUtils.pacificDate('2018-09-29'),
        type: ProjectType.Playlist,
    },
    {
        title: 'Birdcrime',
        url: 'https://birdcrime.vercel.app',
        date: DateUtils.pacificDate('2017-12-03'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Balls',
        url: 'https://man1-balls.vercel.app',
        date: DateUtils.pacificDate('2014-09-22'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Line Fractal Generator',
        url: 'https://line-fractals.vercel.app',
        date: DateUtils.pacificDate('2013-07-22'),
        type: ProjectType.WebApp,
    },
    {
        title: 'Helicopter Game',
        url: 'https://js-heli.vercel.app',
        date: DateUtils.pacificDate('2013-04-16'),
        type: ProjectType.WebApp,
    },
    {
        title: 'WebGL Fireworks',
        url: 'http://www.goldberg.io/fireworks/',
        date: DateUtils.pacificDate('2012-01-10'),
        type: ProjectType.WebApp,
    },
];
